export const enum QuickRouteProviderErrors {
  MISSING_API_KEY = "MISSING_API_KEY",
  MISSING_SEARCH_QUERY = "MISSING_SEARCH_QUERY",
  MISSING_LOGGER = "MISSING_LOGGER",
  MISSING_CACHE = "MISSING_CACHE",
}
