const enum QuickRouteProviderErrors {
  MISSING_PROVIDER_API_KEY = "MISSING_PROVIDER_API_KEY",
  MISSING_PROVIDER_API_PROTOCOL = "MISSING_PROVIDER_API_PROTOCOL",
  MISSING_PROVIDER_API_HOST = "MISSING_PROVIDER_API_HOST",
  MISSING_PROVIDER_SEARCH_QUERY = "MISSING_PROVIDER_SEARCH_QUERY",
  MISSING_PROVIDER_LOGGER = "MISSING_PROVIDER_LOGGER",
  MISSING_PROVIDER_CACHE = "MISSING_PROVIDER_CACHE",
}

export default QuickRouteProviderErrors;
