export enum HttpLogEvents {
  REQUEST = "QUICKROUTE_HTTP_REQUEST",
  REQUEST_ERROR = "QUICKROUTE_HTTP_REQUEST_ERROR",
  RESPONSE = "QUICKROUTE_HTTP_RESPONSE",
  RESPONMSE_ERROR = "QUICKROUTE_HTTP_RESPONSE_ERROR",
}

export enum HttpResponseEvents {
  NOT_FOUND = "QUICKROUTE_HTTP_RESPONSE_NOT_FOUND",
  SERVER_ERROR = "QUICKROUTE_HTTP_RESPONSE_SERVER_ERROR",
  BAD_REQUEST = "QUICKROUTE_HTTP_RESPONSE_BAD_REQUEST",
  UNAUTHORIZED = "QUICKROUTE_HTTP_RESPONSE_UNAUTHORIZED",
}
