export enum HttpLogEvents {
  REQUEST = "QUICKROUTE_HTTP_REQUEST",
  REQUEST_ERROR = "QUICKROUTE_HTTP_REQUEST_ERROR",
  RESPONSE = "QUICKROUTE_HTTP_RESPONSE",
  RESPONSE_ERROR = "QUICKROUTE_HTTP_RESPONSE_ERROR",
}

export enum HttpResponseEventsSuccess {
  SUCCESS = "QUICKROUTE_HTTP_RESPONSE_SUCCESS",
  CREATED = "QUICKROUTE_HTTP_RESPONSE_CREATED",
  NO_CONTENT = "QUICKROUTE_HTTP_RESPONSE_NO_CONTENT",
}
