name: on push to main

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  packages: write
  issues: write
  pull-requests: write

jobs:
  build-library:
    uses: ./.github/workflows/common-build.yml
  quality-checks:
    needs: build-library
    uses: ./.github/workflows/common-quality-check.yml
  release-library:
    needs: quality-checks
    uses: ./.github/workflows/common-release.yml
