name: on pull request

on:
  pull_request:
    branches:
      - '**'

jobs:
  quality-checks:
    uses: ./.github/workflows/common-quality-check.yml
  release-library:
    uses: ./.github/workflows/common-release.yml
    needs: quality-checks